include:
  - board: xiao_ble
    shield: totem_left
  - board: xiao_ble
    shield: totem_right
  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings-reset
# there is no settingsreset (needed) for the XIAO
